//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESAPIX.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESAPIX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(A_Aorta~?(\^[\w\d_\+-]+)?)$	ORGAN
        ///^(A_Aorta_Asc~?(\^[\w\d_\+-]+)?)$	ORGAN
        ///^(A_Brachiocephls~?(\^[\w\d_\+-]+)?)$	ORGAN
        ///^(A_Carotid~?(\^[\w\d_\+-]+)?)$	ORGAN
        ///^(A_Carotid~?_L(\^[\w\d_\+-]+)?)$	ORGAN
        ///^(A_Carotid~?_R(\^[\w\d_\+-]+)?)$	ORGAN
        ///^(A_Celiac~?(\^[\w\d_\+-]+)?)$	ORGAN
        ///^(A_Coronary~?(\^[\w\d_\+-]+)?)$	ORGAN
        ///^(A_Coronary~?_L(\^[\w\d_\+-]+)?)$	ORGAN
        ///^(A_Coronary~?_R(\^[\w\d_\+-]+)?)$	ORGAN
        ///^(A_Femoral_Cflx~?_L(\^[\w\d_\+-]+)?)$	ORGAN
        ///^(A_Femoral_Cflx~?_R(\^[\w\d_\+-]+)?)$	ORGAN
        ///^(A_Femoral~?_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AllowedStructureNames {
            get {
                return ResourceManager.GetString("AllowedStructureNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A_Aorta
        ///A_Aorta_Asc
        ///A_Brachiocephls
        ///A_Carotid
        ///A_Carotid_L
        ///A_Carotid_R
        ///A_Celiac
        ///A_Coronary
        ///A_Coronary_L
        ///A_Coronary_R
        ///A_Femoral_Cflx_L
        ///A_Femoral_Cflx_R
        ///A_Femoral_L
        ///A_Femoral_R
        ///A_Humeral_Cflx_L
        ///A_Humeral_Cflx_R
        ///A_Humeral_L
        ///A_Humeral_R
        ///A_Hypophyseal_I
        ///A_Hypophyseal_S
        ///A_Iliac_Cflx_L
        ///A_Iliac_Cflx_R
        ///A_Iliac_Ext_L
        ///A_Iliac_Ext_R
        ///A_Iliac_Int_L
        ///A_Iliac_Int_R
        ///A_Iliac_L
        ///A_Iliac_R
        ///A_LAD
        ///A_Mesenteric_I
        ///A_Mesenteric_S
        ///A_Pulmonary
        ///A_Subclavian
        ///A_Subclavian_L
        ///A_Subclavian_R
        ///A_Vertebral
        ///A_V [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StructureNamesConcrete {
            get {
                return ResourceManager.GetString("StructureNamesConcrete", resourceCulture);
            }
        }
    }
}
